<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ik_faq"
 *
 * Auto generated by Extension Builder 2014-05-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FAQ - Frequently Asked Questions // Ingo Kasch',
	'description' => 'ik_faq is a TYPO3 extension for managing and displaying a FAQ section on your website',
	'category' => 'plugin',
	'author' => 'Ingo Kasch',
	'author_email' => 'ingo.kasch@loom-dxp.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '9.5.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '9.5.0-9.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
